# =============================================================================
# Neo4j - Pod for Podman Desktop
# =============================================================================
# Run with: podman kube play openshift/neo4j/pod.yaml
# Stop with: podman kube down openshift/neo4j/pod.yaml
#
# Neo4j Browser: http://localhost:7474
# Bolt URI: bolt://localhost:7687
# =============================================================================
apiVersion: v1
kind: Pod
metadata:
  name: neo4j-pod
  labels:
    app: neo4j
spec:
  containers:
    - name: neo4j
      image: docker.io/library/neo4j:5-community
      ports:
        - containerPort: 7474
          hostPort: 7474
          name: http
        - containerPort: 7687
          hostPort: 7687
          name: bolt
      env:
        # Default credentials - change NEO4J_AUTH for production!
        - name: NEO4J_AUTH
          value: "neo4j/fsi-graphrag-2024"
        # Enable APOC plugin
        - name: NEO4J_PLUGINS
          value: '["apoc"]'
        # Memory settings (adjust based on your machine)
        - name: NEO4J_server_memory_heap_initial__size
          value: "512m"
        - name: NEO4J_server_memory_heap_max__size
          value: "1G"
      volumeMounts:
        - name: neo4j-data
          mountPath: /data
  volumes:
    - name: neo4j-data
      emptyDir: {}
